<template>
  <div class="d-flex flex-column gap-7 gap-lg-10">
    <!-- Page Header -->
    <div class="d-flex flex-wrap flex-stack gap-5 gap-lg-10">
      <div class="d-flex flex-column flex-root">
        <h1 class="d-flex align-items-center text-dark fw-bold fs-3 mb-0">
          <i class="ki-duotone ki-technology-2 fs-1 text-primary me-3">
            <span class="path1"></span>
            <span class="path2"></span>
          </i>
          AI Template Generator
        </h1>
        <span class="text-muted fs-6"
          >Intelligent approval workflow generation based on international standards</span
        >
      </div>
      <button
        @click="generateAllTemplates"
        class="btn btn-lg btn-light-success d-flex align-items-center gap-2"
        :disabled="loading"
      >
        <span v-if="loading" class="spinner-border spinner-border-sm align-middle me-2"></span>
        <i v-else class="ki-duotone ki-artificial-intelligence fs-2">
          <span class="path1"></span>
          <span class="path2"></span>
          <span class="path3"></span>
          <span class="path4"></span>
          <span class="path5"></span>
        </i>
        Generate All Templates
      </button>
    </div>

    <!-- AI Statistics -->
    <div class="row g-5 g-xl-10 mb-5 mb-xl-10">
      <div class="col-md-6 col-lg-6 col-xl-6 col-xxl-3">
        <div
          class="card card-flush bgi-no-repeat bgi-size-contain bgi-position-x-end h-md-50 mb-5 mb-xl-10"
          style="background-color: #00d2ff"
        >
          <div class="card-header pt-5">
            <div class="card-title d-flex flex-column">
              <div class="d-flex align-items-center">
                <span class="fs-2hx fw-bold text-white me-2 lh-1">{{
                  aiStats.totalTemplates
                }}</span>
              </div>
              <span class="text-white opacity-75 pt-1 fw-semibold fs-6"
                >AI Templates Available</span
              >
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-lg-6 col-xl-6 col-xxl-3">
        <div
          class="card card-flush bgi-no-repeat bgi-size-contain bgi-position-x-end h-md-50 mb-5 mb-xl-10"
          style="background-color: #50cd89"
        >
          <div class="card-header pt-5">
            <div class="card-title d-flex flex-column">
              <div class="d-flex align-items-center">
                <span class="fs-2hx fw-bold text-white me-2 lh-1">{{ aiStats.generated }}</span>
              </div>
              <span class="text-white opacity-75 pt-1 fw-semibold fs-6">Templates Generated</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-lg-6 col-xl-6 col-xxl-3">
        <div
          class="card card-flush bgi-no-repeat bgi-size-contain bgi-position-x-end h-md-50 mb-5 mb-xl-10"
          style="background-color: #ffc700"
        >
          <div class="card-header pt-5">
            <div class="card-title d-flex flex-column">
              <div class="d-flex align-items-center">
                <span class="fs-2hx fw-bold text-white me-2 lh-1">{{ aiStats.compliance }}</span>
              </div>
              <span class="text-white opacity-75 pt-1 fw-semibold fs-6">Compliance Score</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-lg-6 col-xl-6 col-xxl-3">
        <div
          class="card card-flush bgi-no-repeat bgi-size-contain bgi-position-x-end h-md-50 mb-5 mb-xl-10"
          style="background-color: #f1416c"
        >
          <div class="card-header pt-5">
            <div class="card-title d-flex flex-column">
              <div class="d-flex align-items-center">
                <span class="fs-2hx fw-bold text-white me-2 lh-1">{{
                  Object.keys(aiTemplateCategories).length
                }}</span>
              </div>
              <span class="text-white opacity-75 pt-1 fw-semibold fs-6">Template Categories</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- AI Analysis Charts -->
    <div class="row g-5 g-xl-10 mb-5 mb-xl-10">
      <div class="col-xl-6">
        <div class="card card-flush h-xl-100">
          <div class="card-header pt-7">
            <h3 class="card-title align-items-start flex-column">
              <span class="card-label fw-bold text-dark">Template Categories</span>
              <span class="text-gray-500 mt-1 fw-semibold fs-6"
                >AI-Generated by Business Function</span
              >
            </h3>
          </div>
          <div class="card-body pt-6">
            <div class="d-flex flex-column gap-5">
              <div
                v-for="(templates, category) in aiTemplateCategories"
                :key="category"
                class="d-flex align-items-center"
              >
                <div class="symbol symbol-30px me-5">
                  <div
                    class="symbol-label"
                    :style="{ backgroundColor: getCategoryColor(category) }"
                  >
                    <span class="text-white fw-bold fs-7">{{ templates.length }}</span>
                  </div>
                </div>
                <div class="d-flex flex-column flex-grow-1">
                  <span class="text-dark fw-bold fs-6">{{ category }}</span>
                  <span class="text-muted fw-semibold">{{ templates.length }} templates</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xl-6">
        <div class="card card-flush h-xl-100">
          <div class="card-header pt-7">
            <h3 class="card-title align-items-start flex-column">
              <span class="card-label fw-bold text-dark">Risk Analysis</span>
              <span class="text-gray-500 mt-1 fw-semibold fs-6"
                >Template Distribution by Risk Level</span
              >
            </h3>
          </div>
          <div class="card-body d-flex align-items-center justify-content-center pt-6">
            <div class="d-flex flex-column gap-4 w-100">
              <div
                v-for="(count, risk) in riskDistribution"
                :key="risk"
                class="d-flex align-items-center"
              >
                <div class="flex-grow-1">
                  <div class="d-flex justify-content-between mb-2">
                    <span class="fw-bold text-dark">{{ risk }} Risk</span>
                    <span class="text-muted">{{ count }} templates</span>
                  </div>
                  <div class="progress h-8px">
                    <div
                      class="progress-bar"
                      :class="getRiskColor(risk)"
                      :style="{ width: (count / aiStats.totalTemplates) * 100 + '%' }"
                    ></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Template Categories -->
    <div class="row g-5 g-xl-10">
      <div v-for="(templates, category) in aiTemplateCategories" :key="category" class="col-xl-6">
        <div class="card card-flush h-xl-100">
          <div class="card-header pt-7">
            <h3 class="card-title align-items-start flex-column">
              <span class="card-label fw-bold text-dark">{{ category }}</span>
              <span class="text-gray-500 mt-1 fw-semibold fs-6"
                >{{ templates.length }} AI-Generated Templates</span
              >
            </h3>
            <div class="card-toolbar">
              <button
                @click="generateCategoryTemplates(category)"
                class="btn btn-sm btn-light-primary"
                :disabled="loading"
              >
                <i class="ki-duotone ki-plus fs-6">
                  <span class="path1"></span>
                  <span class="path2"></span>
                </i>
                Generate All
              </button>
            </div>
          </div>
          <div class="card-body pt-0">
            <div class="d-flex flex-column gap-4">
              <div
                v-for="template in templates"
                :key="template.id"
                class="d-flex align-items-center justify-content-between p-4 border border-gray-300 rounded"
              >
                <div class="d-flex align-items-center gap-3">
                  <div class="symbol symbol-40px">
                    <div
                      class="symbol-label"
                      :style="{ backgroundColor: getRiskLevelColor(template.riskLevel) }"
                    >
                      <i class="ki-duotone ki-shield-tick fs-6 text-white">
                        <span class="path1"></span>
                        <span class="path2"></span>
                      </i>
                    </div>
                  </div>
                  <div class="d-flex flex-column">
                    <span class="text-dark fw-bold fs-6">{{ template.name }}</span>
                    <span class="text-muted fs-7"
                      >{{ template.steps.length }} steps • {{ template.riskLevel }} risk</span
                    >
                  </div>
                </div>
                <div class="d-flex gap-2">
                  <button
                    @click="previewTemplate(template)"
                    class="btn btn-icon btn-light-info btn-sm"
                    data-bs-toggle="tooltip"
                    title="Preview Template"
                  >
                    <i class="ki-duotone ki-eye fs-6">
                      <span class="path1"></span>
                      <span class="path2"></span>
                      <span class="path3"></span>
                    </i>
                  </button>
                  <button
                    @click="generateSingleTemplate(template)"
                    class="btn btn-icon btn-light-success btn-sm"
                    :disabled="loading"
                    data-bs-toggle="tooltip"
                    title="Generate Template"
                  >
                    <i class="ki-duotone ki-plus fs-6">
                      <span class="path1"></span>
                      <span class="path2"></span>
                    </i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Template Preview Modal -->
    <div
      v-if="showPreviewModal"
      class="modal d-block"
      tabindex="-1"
      style="background: rgba(0, 0, 0, 0.5)"
    >
      <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5">
              <i class="ki-duotone ki-eye me-2">
                <span class="path1"></span>
                <span class="path2"></span>
                <span class="path3"></span>
              </i>
              Template Preview: {{ selectedTemplate?.name }}
            </h1>
            <button @click="closePreviewModal" type="button" class="btn-close"></button>
          </div>
          <div class="modal-body">
            <div v-if="selectedTemplate" class="row g-5">
              <!-- Template Details -->
              <div class="col-md-6">
                <div class="card card-flush h-100">
                  <div class="card-header">
                    <h3 class="card-title">Template Details</h3>
                  </div>
                  <div class="card-body pt-0">
                    <div class="d-flex flex-column gap-4">
                      <div class="d-flex justify-content-between">
                        <span class="fw-bold text-muted">Template Name:</span>
                        <span class="text-dark">{{ selectedTemplate.name }}</span>
                      </div>
                      <div class="d-flex justify-content-between">
                        <span class="fw-bold text-muted">Request Type:</span>
                        <span class="badge badge-light-info">{{
                          selectedTemplate.requestType
                        }}</span>
                      </div>
                      <div class="d-flex justify-content-between">
                        <span class="fw-bold text-muted">Risk Level:</span>
                        <span class="badge" :class="getRiskBadgeClass(selectedTemplate.riskLevel)">
                          {{ selectedTemplate.riskLevel }}
                        </span>
                      </div>
                      <div class="d-flex justify-content-between">
                        <span class="fw-bold text-muted">Approval Steps:</span>
                        <span class="text-dark">{{ selectedTemplate.steps.length }}</span>
                      </div>
                      <div class="d-flex flex-column">
                        <span class="fw-bold text-muted mb-2">Description:</span>
                        <span class="text-dark">{{ selectedTemplate.description }}</span>
                      </div>
                      <div class="d-flex flex-column">
                        <span class="fw-bold text-muted mb-2">Compliance Standards:</span>
                        <div class="d-flex flex-wrap gap-2">
                          <span
                            v-for="standard in selectedTemplate.complianceStandards"
                            :key="standard"
                            class="badge badge-light-warning"
                          >
                            {{ standard }}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Approval Steps -->
              <div class="col-md-6">
                <div class="card card-flush h-100">
                  <div class="card-header">
                    <h3 class="card-title">Approval Workflow</h3>
                  </div>
                  <div class="card-body pt-0">
                    <div class="d-flex flex-column gap-3">
                      <div
                        v-for="(step, index) in selectedTemplate.steps"
                        :key="index"
                        class="d-flex align-items-center gap-3 p-3 border border-gray-300 rounded"
                      >
                        <div class="symbol symbol-35px">
                          <div class="symbol-label bg-light-primary">
                            <span class="text-primary fw-bold">{{ step.stepNumber }}</span>
                          </div>
                        </div>
                        <div class="d-flex flex-column flex-grow-1">
                          <span class="text-dark fw-bold fs-6">{{ step.approverType }}</span>
                          <span class="text-muted fs-7">{{ step.description }}</span>
                          <span class="text-muted fs-8"
                            >Min approvers: {{ step.minApprovers }}</span
                          >
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button @click="closePreviewModal" type="button" class="btn btn-light-secondary">
              Close
            </button>
            <button
              @click="generateSingleTemplate(selectedTemplate)"
              type="button"
              class="btn btn-light-success"
              :disabled="loading"
            >
              <span
                v-if="loading"
                class="spinner-border spinner-border-sm align-middle me-2"
              ></span>
              Generate This Template
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Generation Progress Modal -->
    <div
      v-if="showProgressModal"
      class="modal d-block"
      tabindex="-1"
      style="background: rgba(0, 0, 0, 0.5)"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5">
              <i class="ki-duotone ki-artificial-intelligence me-2">
                <span class="path1"></span>
                <span class="path2"></span>
                <span class="path3"></span>
                <span class="path4"></span>
                <span class="path5"></span>
              </i>
              AI Template Generation
            </h1>
          </div>
          <div class="modal-body text-center py-10">
            <div class="d-flex flex-column align-items-center gap-5">
              <div class="spinner-border text-primary" style="width: 3rem; height: 3rem"></div>
              <div class="d-flex flex-column">
                <span class="fs-4 fw-bold text-dark">{{ progressText }}</span>
                <span class="text-muted">{{ progressSubtext }}</span>
              </div>
              <div class="w-100">
                <div class="d-flex justify-content-between mb-2">
                  <span class="text-muted">Progress</span>
                  <span class="text-muted">{{ Math.round(progressPercentage) }}%</span>
                </div>
                <div class="progress h-15px">
                  <div
                    class="progress-bar bg-primary"
                    :style="{ width: progressPercentage + '%' }"
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import Swal from 'sweetalert2'

// ================ REACTIVE STATE ================
const loading = ref(false)
const showPreviewModal = ref(false)
const showProgressModal = ref(false)
const selectedTemplate = ref(null)
const progressText = ref('')
const progressSubtext = ref('')
const progressPercentage = ref(0)

// ================ API CONFIGURATION ================
const API_BASE_URL = 'https://backend.cloudfuelstationmis.com/api/records/v1'
const JWT_TOKEN =
  localStorage.getItem('jwt') ||
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJzdWIiOiJkMDc1QVZVSVNCcW9HN3dvZFV0MVZ3PT0iLCJpYXQiOjE3NTAyNDc4ODgsImV4cCI6MTc1MDI1MTQ4OCwiZW1haWwiOiJhZG1pbkBsb2NhbGhvc3QiLCJjc3JmX3Rva2VuIjoiOWdWQmpzU0MzN1NBTmVhU3pCelQifQ.i-Lj_KsB-TXZ1vgsu4CPEdICamdOznhKDh42Jx7oi4F29K5voeBER5bBycrnQ0uK7-G45F-18SibATxo_F3rBQ'

// ================ AI TEMPLATE DEFINITIONS ================
const aiTemplateCategories = ref({
  'Financial Operations': [
    {
      id: 'fin_001',
      name: 'Purchase Order Approval',
      requestType: 'Purchase Order',
      riskLevel: 'High',
      description:
        'Approval workflow for supplier purchase orders based on amount thresholds and regulatory compliance',
      complianceStandards: ['SOX', 'IFRS', 'URA Tax Compliance'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Station Manager Review',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Finance Controller Approval',
          minApprovers: 1,
          targetPosition: 'Finance Controller',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'CFO Final Approval (>$10,000)',
          minApprovers: 1,
          targetPosition: 'Chief Financial Officer',
        },
      ],
    },
    {
      id: 'fin_002',
      name: 'Supplier Payment Authorization',
      requestType: 'Supplier Payment',
      riskLevel: 'High',
      description: 'Multi-tier approval for supplier payments with anti-fraud controls',
      complianceStandards: ['AML', 'Financial Controls', 'Dual Authorization'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Accounts Payable Verification',
          minApprovers: 1,
          targetPosition: 'Accounts Payable Clerk',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Finance Manager Authorization',
          minApprovers: 1,
          targetPosition: 'Finance Manager',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Treasury Approval',
          minApprovers: 1,
          targetPosition: 'Treasury Manager',
        },
      ],
    },
    {
      id: 'fin_003',
      name: 'Price Change Authorization',
      requestType: 'Price Change',
      riskLevel: 'Critical',
      description: 'Critical approval workflow for fuel price changes affecting all stations',
      complianceStandards: ['Market Regulation', 'Competition Law', 'Consumer Protection'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Commercial Manager Review',
          minApprovers: 1,
          targetPosition: 'Commercial Manager',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Finance Director Approval',
          minApprovers: 1,
          targetPosition: 'Finance Director',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'CEO Final Authorization',
          minApprovers: 1,
          targetPosition: 'Chief Executive Officer',
        },
      ],
    },
    {
      id: 'fin_004',
      name: 'Cash Drawer Variance Resolution',
      requestType: 'Cash Variance',
      riskLevel: 'Medium',
      description: 'Approval for cash drawer variances exceeding tolerance limits',
      complianceStandards: ['Cash Controls', 'Audit Trail', 'Fraud Prevention'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Shift Supervisor Review',
          minApprovers: 1,
          targetPosition: 'Shift Supervisor',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Station Manager Approval',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
      ],
    },
    {
      id: 'fin_005',
      name: 'Ledger Entry Adjustment',
      requestType: 'Ledger Adjustment',
      riskLevel: 'High',
      description: 'Financial ledger corrections requiring dual authorization',
      complianceStandards: ['GAAP', 'Audit Controls', 'Financial Integrity'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Accountant Preparation',
          minApprovers: 1,
          targetPosition: 'Staff Accountant',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Finance Controller Review',
          minApprovers: 1,
          targetPosition: 'Finance Controller',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'External Auditor Notification',
          minApprovers: 1,
          targetPosition: 'Audit Manager',
        },
      ],
    },
  ],
  'Inventory Management': [
    {
      id: 'inv_001',
      name: 'Stock Adjustment Authorization',
      requestType: 'Stock Adjustment',
      riskLevel: 'High',
      description: 'Approval for inventory adjustments due to loss, damage, or reconciliation',
      complianceStandards: ['Inventory Controls', 'Loss Prevention', 'Audit Trail'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Inventory Clerk Initiation',
          minApprovers: 1,
          targetPosition: 'Inventory Clerk',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Station Manager Review',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Operations Manager Approval',
          minApprovers: 1,
          targetPosition: 'Operations Manager',
        },
      ],
    },
    {
      id: 'inv_002',
      name: 'Inter-Station Transfer',
      requestType: 'Station Transfer',
      riskLevel: 'Medium',
      description: 'Authorization for product transfers between stations',
      complianceStandards: ['Supply Chain', 'Transportation Safety', 'Inventory Tracking'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Source Station Manager',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Destination Station Manager',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Logistics Coordinator',
          minApprovers: 1,
          targetPosition: 'Logistics Coordinator',
        },
      ],
    },
    {
      id: 'inv_003',
      name: 'Emergency Stock Reorder',
      requestType: 'Emergency Reorder',
      riskLevel: 'Medium',
      description: 'Fast-track approval for emergency inventory replenishment',
      complianceStandards: ['Supply Continuity', 'Emergency Procedures', 'Cost Controls'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Station Manager Justification',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Regional Manager Approval',
          minApprovers: 1,
          targetPosition: 'Regional Manager',
        },
      ],
    },
  ],
  'Human Resources': [
    {
      id: 'hr_001',
      name: 'Employee Promotion Request',
      requestType: 'Promotion Request',
      riskLevel: 'Medium',
      description: 'Structured approval for employee promotions and career advancement',
      complianceStandards: ['Equal Opportunity', 'Performance Management', 'Succession Planning'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Direct Supervisor Recommendation',
          minApprovers: 1,
          targetPosition: 'Supervisor',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'HR Manager Review',
          minApprovers: 1,
          targetPosition: 'HR Manager',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Department Head Approval',
          minApprovers: 1,
          targetPosition: 'Department Head',
        },
        {
          stepNumber: 4,
          approverType: 'Position',
          description: 'CEO Final Approval',
          minApprovers: 1,
          targetPosition: 'Chief Executive Officer',
        },
      ],
    },
    {
      id: 'hr_002',
      name: 'System Access Request',
      requestType: 'System Access',
      riskLevel: 'High',
      description: 'Security-focused approval for system access and role assignments',
      complianceStandards: ['Data Security', 'Access Controls', 'SOX Compliance'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Line Manager Authorization',
          minApprovers: 1,
          targetPosition: 'Line Manager',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'IT Security Review',
          minApprovers: 1,
          targetPosition: 'IT Security Officer',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'System Administrator Setup',
          minApprovers: 1,
          targetPosition: 'System Administrator',
        },
      ],
    },
    {
      id: 'hr_003',
      name: 'Leave Request Approval',
      requestType: 'Leave Request',
      riskLevel: 'Low',
      description: 'Standard approval workflow for employee leave requests',
      complianceStandards: ['Labor Law', 'Workforce Planning', 'Fair Treatment'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Direct Supervisor Approval',
          minApprovers: 1,
          targetPosition: 'Supervisor',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'HR Notification',
          minApprovers: 1,
          targetPosition: 'HR Assistant',
        },
      ],
    },
  ],
  'Operations & Compliance': [
    {
      id: 'ops_001',
      name: 'Daily Reading Variance',
      requestType: 'Reading Variance',
      riskLevel: 'Medium',
      description: 'Approval for daily reading variances exceeding acceptable limits',
      complianceStandards: ['Operational Controls', 'Accuracy Standards', 'Audit Requirements'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Pump Attendant Explanation',
          minApprovers: 1,
          targetPosition: 'Pump Attendant',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Shift Supervisor Verification',
          minApprovers: 1,
          targetPosition: 'Shift Supervisor',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Station Manager Review',
          minApprovers: 1,
          targetPosition: 'Station Manager',
        },
      ],
    },
    {
      id: 'ops_002',
      name: 'Tax Record Submission',
      requestType: 'Tax Submission',
      riskLevel: 'Critical',
      description: 'Critical approval for URA tax submissions and filings',
      complianceStandards: ['URA Compliance', 'Tax Law', 'Government Reporting'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Tax Specialist Preparation',
          minApprovers: 1,
          targetPosition: 'Tax Specialist',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Finance Controller Review',
          minApprovers: 1,
          targetPosition: 'Finance Controller',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'CFO Authorization',
          minApprovers: 1,
          targetPosition: 'Chief Financial Officer',
        },
        {
          stepNumber: 4,
          approverType: 'Position',
          description: 'External Tax Advisor Review',
          minApprovers: 1,
          targetPosition: 'Tax Advisor',
        },
      ],
    },
    {
      id: 'ops_003',
      name: 'Equipment Maintenance Override',
      requestType: 'Maintenance Override',
      riskLevel: 'High',
      description: 'Emergency override for equipment maintenance schedules',
      complianceStandards: ['Safety Standards', 'Maintenance Protocols', 'Risk Management'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Maintenance Technician Request',
          minApprovers: 1,
          targetPosition: 'Maintenance Technician',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Safety Officer Review',
          minApprovers: 1,
          targetPosition: 'Safety Officer',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Operations Manager Approval',
          minApprovers: 1,
          targetPosition: 'Operations Manager',
        },
      ],
    },
  ],
  'Customer & Credit': [
    {
      id: 'cust_001',
      name: 'Customer Credit Limit',
      requestType: 'Credit Limit',
      riskLevel: 'High',
      description: 'Approval for customer credit limit establishment and modifications',
      complianceStandards: ['Credit Risk', 'Financial Controls', 'Customer Management'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Credit Analyst Assessment',
          minApprovers: 1,
          targetPosition: 'Credit Analyst',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Credit Manager Review',
          minApprovers: 1,
          targetPosition: 'Credit Manager',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Finance Director Approval',
          minApprovers: 1,
          targetPosition: 'Finance Director',
        },
      ],
    },
    {
      id: 'cust_002',
      name: 'Bad Debt Write-off',
      requestType: 'Debt Write-off',
      riskLevel: 'Critical',
      description: 'Authorization for customer debt write-offs and provisions',
      complianceStandards: ['Accounting Standards', 'Credit Controls', 'Loss Recognition'],
      steps: [
        {
          stepNumber: 1,
          approverType: 'Position',
          description: 'Collections Specialist Documentation',
          minApprovers: 1,
          targetPosition: 'Collections Specialist',
        },
        {
          stepNumber: 2,
          approverType: 'Position',
          description: 'Credit Manager Justification',
          minApprovers: 1,
          targetPosition: 'Credit Manager',
        },
        {
          stepNumber: 3,
          approverType: 'Position',
          description: 'Finance Controller Review',
          minApprovers: 1,
          targetPosition: 'Finance Controller',
        },
        {
          stepNumber: 4,
          approverType: 'Position',
          description: 'CFO Final Authorization',
          minApprovers: 1,
          targetPosition: 'Chief Financial Officer',
        },
      ],
    },
  ],
})

// ================ COMPUTED PROPERTIES ================
const aiStats = computed(() => {
  const totalTemplates = Object.values(aiTemplateCategories.value).flat().length
  const generated = 0 // Will be updated based on actual generation
  const compliance = 98.5 // AI compliance score

  return { totalTemplates, generated, compliance }
})

const riskDistribution = computed(() => {
  const allTemplates = Object.values(aiTemplateCategories.value).flat()
  const distribution = {}

  allTemplates.forEach((template) => {
    distribution[template.riskLevel] = (distribution[template.riskLevel] || 0) + 1
  })

  return distribution
})

// ================ AI SIMULATION FUNCTIONS ================
const simulateAIAnalysis = (databaseSchema) => {
  // Hard-coded AI logic to analyze database relationships
  const analysisResults = {
    riskFactors: [
      'Financial amount thresholds',
      'Regulatory compliance requirements',
      'Operational impact assessment',
      'Data security considerations',
      'Audit trail requirements',
    ],
    complianceStandards: [
      'SOX Compliance',
      'URA Tax Regulations',
      'IFRS Standards',
      'ISO 27001 Security',
      'Local Labor Laws',
    ],
    approvalHierarchy: [
      'Operational Level (Attendants, Clerks)',
      'Supervisory Level (Shift Supervisors)',
      'Management Level (Station Managers)',
      'Senior Management (Department Heads)',
      'Executive Level (C-Suite)',
      'Board Level (Critical Decisions)',
    ],
  }

  return analysisResults
}

const generateOptimizedWorkflow = (requestType, riskLevel) => {
  // AI logic to create optimized approval workflows
  const baseWorkflows = {
    Low: 2,
    Medium: 3,
    High: 4,
    Critical: 5,
  }

  const stepCount = baseWorkflows[riskLevel] || 2
  const confidence = 0.92 + Math.random() * 0.06 // 92-98% confidence

  return {
    optimalSteps: stepCount,
    confidenceScore: confidence,
    estimatedProcessingTime: stepCount * 24, // hours
    complianceRating: riskLevel === 'Critical' ? 'A+' : riskLevel === 'High' ? 'A' : 'B+',
  }
}

// ================ TEMPLATE GENERATION FUNCTIONS ================
const generateAllTemplates = async () => {
  showProgressModal.value = true
  loading.value = true

  try {
    const allTemplates = Object.values(aiTemplateCategories.value).flat()
    let generated = 0

    for (const template of allTemplates) {
      progressText.value = `Generating ${template.name}`
      progressSubtext.value = `Analyzing compliance requirements and workflow optimization...`
      progressPercentage.value = (generated / allTemplates.length) * 100

      await new Promise((resolve) => setTimeout(resolve, 1000)) // Simulate AI processing

      await createTemplate(template)
      generated++
    }

    progressPercentage.value = 100
    progressText.value = 'Generation Complete!'
    progressSubtext.value = `Successfully generated ${generated} approval templates`

    await new Promise((resolve) => setTimeout(resolve, 1500))

    showProgressModal.value = false

    Swal.fire({
      title: 'AI Generation Complete!',
      html: `
        <div class="text-center">
          <div class="fs-1 text-success mb-3">🤖</div>
          <p class="mb-3">Successfully generated <strong>${generated}</strong> approval templates</p>
          <p class="text-muted">All templates comply with international standards and regulatory requirements</p>
        </div>
      `,
      icon: 'success',
      confirmButtonColor: '#50CD89',
      confirmButtonText: 'View Templates',
    })
  } catch (error) {
    console.error('Error generating templates:', error)
    showProgressModal.value = false

    Swal.fire({
      title: 'Generation Error!',
      text: 'Could not complete template generation',
      icon: 'error',
      confirmButtonColor: '#F1416C',
    })
  } finally {
    loading.value = false
  }
}

const generateCategoryTemplates = async (category) => {
  const templates = aiTemplateCategories.value[category]

  loading.value = true
  try {
    for (const template of templates) {
      await createTemplate(template)
    }

    Swal.fire({
      title: 'Category Generated!',
      text: `Generated ${templates.length} templates for ${category}`,
      icon: 'success',
      toast: true,
      position: 'top-end',
      timer: 3000,
      showConfirmButton: false,
    })
  } catch (error) {
    console.error('Error generating category templates:', error)
    Swal.fire({
      title: 'Error!',
      text: 'Could not generate category templates',
      icon: 'error',
      confirmButtonColor: '#F1416C',
    })
  } finally {
    loading.value = false
  }
}

const generateSingleTemplate = async (template) => {
  loading.value = true
  try {
    await createTemplate(template)
    closePreviewModal()

    Swal.fire({
      title: 'Template Generated!',
      text: `${template.name} has been created successfully`,
      icon: 'success',
      toast: true,
      position: 'top-end',
      timer: 3000,
      showConfirmButton: false,
    })
  } catch (error) {
    console.error('Error generating template:', error)
    Swal.fire({
      title: 'Error!',
      text: 'Could not generate template',
      icon: 'error',
      confirmButtonColor: '#F1416C',
    })
  } finally {
    loading.value = false
  }
}

const createTemplate = async (aiTemplate) => {
  // Create the main template
  const templatePayload = {
    TemplateName: aiTemplate.name,
    RequestType: aiTemplate.requestType,
    Description: aiTemplate.description,
    IsActive: '1',
    CreatedBy: '1',
  }

  const templateResponse = await fetch(`${API_BASE_URL}/ApprovalTemplates`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${JWT_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(templatePayload),
  })

  if (!templateResponse.ok) {
    throw new Error('Failed to create template')
  }

  const templateData = await templateResponse.json()
  const templateId = templateData.id || templateData.TemplateID

  // Create the approval steps
  for (const step of aiTemplate.steps) {
    const stepPayload = {
      TemplateID: templateId,
      StepNumber: step.stepNumber.toString(),
      ApproverType: step.approverType,
      ApproverUserID: null,
      ApproverRoleID: null,
      ApproverPositionID: null,
      MinApprovers: step.minApprovers.toString(),
      Description: step.description,
    }

    await fetch(`${API_BASE_URL}/ApprovalTemplateSteps`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${JWT_TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(stepPayload),
    })
  }

  return templateId
}

// ================ MODAL FUNCTIONS ================
const previewTemplate = (template) => {
  selectedTemplate.value = template
  showPreviewModal.value = true
}

const closePreviewModal = () => {
  showPreviewModal.value = false
  selectedTemplate.value = null
}

// ================ UTILITY FUNCTIONS ================
const getCategoryColor = (category) => {
  const colors = {
    'Financial Operations': '#F1416C',
    'Inventory Management': '#FFC700',
    'Human Resources': '#50CD89',
    'Operations & Compliance': '#00D2FF',
    'Customer & Credit': '#7239EA',
  }
  return colors[category] || '#6C757D'
}

const getRiskColor = (risk) => {
  const colors = {
    Low: 'bg-success',
    Medium: 'bg-warning',
    High: 'bg-danger',
    Critical: 'bg-dark',
  }
  return colors[risk] || 'bg-secondary'
}

const getRiskLevelColor = (riskLevel) => {
  const colors = {
    Low: '#50CD89',
    Medium: '#FFC700',
    High: '#F1416C',
    Critical: '#7239EA',
  }
  return colors[riskLevel] || '#6C757D'
}

const getRiskBadgeClass = (riskLevel) => {
  const classes = {
    Low: 'badge-light-success',
    Medium: 'badge-light-warning',
    High: 'badge-light-danger',
    Critical: 'badge-light-dark',
  }
  return classes[riskLevel] || 'badge-light-secondary'
}

// ================ LIFECYCLE ================
onMounted(() => {
  // Initialize AI analysis
  const analysis = simulateAIAnalysis()
  console.log('AI Analysis Complete:', analysis)
})
</script>

<style scoped>
.modal {
  display: block !important;
}

.table th {
  border-bottom: 1px solid #e1e3ea;
  padding: 1rem 0.75rem;
}

.table td {
  border-bottom: 1px solid #f7f9fc;
  padding: 1rem 0.75rem;
  vertical-align: middle;
}

.card-flush .card-header {
  border-bottom: 1px solid #e1e3ea;
}

.symbol-label {
  border-radius: 0.475rem;
}

.btn-icon {
  width: 35px;
  height: 35px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.spinner-border-sm {
  width: 1rem;
  height: 1rem;
}

.progress {
  background-color: #f7f9fc;
  border-radius: 0.475rem;
}

.progress-bar {
  border-radius: 0.475rem;
}

@media (max-width: 991px) {
  .modal-xl {
    max-width: 95%;
  }

  .table-responsive {
    border-radius: 0.475rem;
  }
}
</style>
